### ISSUE TITLE
Command Missing

### ISSUE THREAD

**Issue by sibzz** [hweidner/galera-docker#1]
Hey thanks for the script. it works!
| wsrep_incoming_addresses      | 172.18.0.103:3306,172.18.0.102:3306,172.18.0.101:3306 |

 Small issue however Node 2 & Node 3 immediately go into restart mode and log shows below error:
[ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
        You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD

Solution is simple (provide password for node2 & node3 as well in the docker run command):

docker run -d --restart=unless-stopped --net galera --name node3 -h node3 --ip 172.18.0.103 -p 3313:3306 -v /srv/galera/node3.cnf:/etc/mysql/conf.d/galera.cnf -v /srv/galera/node3:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=secret_galera_password \ hweidner/galera

docker run -d --restart=unless-stopped --net galera --name node3 -h node3 --ip 172.18.0.103 -p 3313:3306 -v /srv/galera/node3.cnf:/etc/mysql/conf.d/galera.cnf -v /srv/galera/node3:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=secret_galera_password  hweidner/galera

**Comment by hweidner** [comment]
Thank you for reporting this.
I altered the command to use the MYSQL_ALLOW_EMPTY_PASSWORD variable, as the data (including the mysql.user database) is transferred from the first node and no further actions needs to be done.
